import type { CaseDetail, CaseRecord } from "./types";

export const demoCases: CaseRecord[] = [
  {
    id: "demo-1",
    case_ref: "MYB-2026-000012",
    status: "COMMUNICATED",
    category: "unauthorized_transaction",
    urgency: "High",
    confidence: 1,
    amount_rm: 890,
    verification_result: "PASS",
    outcome: "RESOLVED_IN_FULL",
    account_no_masked: "******1233",
    sla_due: "2026-08-05T09:15:00+08:00",
    summary: "Customer disputes an overnight TECHWORLD KL debit.",
    channel: "MANUAL_INJECT",
    created_at: "2026-08-04T00:25:00+08:00",
  },
  {
    id: "demo-2",
    case_ref: "MYB-2026-000014",
    status: "REVIEW_PENDING",
    category: "billing_error",
    urgency: "Medium",
    confidence: 0.82,
    amount_rm: 486.2,
    verification_result: "PASS",
    outcome: "PENDING",
    account_no_masked: "******7788",
    sla_due: "2026-08-27T17:00:00+08:00",
    summary: "Duplicate annual service fee needs a human approval.",
    channel: "WORKBUDDY_EMAIL_MCP",
    created_at: "2026-08-04T00:31:00+08:00",
  },
  {
    id: "demo-3",
    case_ref: "MYB-2026-000015",
    status: "VERIFIED",
    category: "atm_debit_card",
    urgency: "High",
    confidence: 0.91,
    amount_rm: 500,
    verification_result: "MANUAL_REVIEW",
    outcome: "PENDING",
    account_no_masked: "******9900",
    sla_due: "2026-08-11T12:00:00+08:00",
    summary: "ATM dispensed RM400 against a RM500 debit.",
    channel: "BRANCH_BOT",
    created_at: "2026-08-04T00:36:00+08:00",
  },
  {
    id: "demo-4",
    case_ref: "MYB-2026-000013",
    status: "QUARANTINED",
    category: null,
    urgency: null,
    confidence: null,
    amount_rm: 1_000_000,
    verification_result: null,
    outcome: "PENDING",
    account_no_masked: null,
    summary: "Prompt-injection attempt blocked before model access.",
    channel: "MANUAL_INJECT",
    created_at: "2026-08-04T00:26:00+08:00",
  },
  {
    id: "demo-5",
    case_ref: "MYB-2026-000016",
    status: "CLASSIFIED",
    category: "mis_selling",
    urgency: "Medium",
    confidence: 0.88,
    amount_rm: 12_000,
    verification_result: null,
    outcome: "PENDING",
    account_no_masked: "******2233",
    summary: "Customer says capital protection was promised but absent.",
    channel: "IMAP",
    created_at: "2026-08-04T00:42:00+08:00",
  },
];

export const demoDetail: CaseDetail = {
  case: demoCases[0],
  chain: { ok: true, first_bad_seq: null, reason: null },
  cost_rm: 0.008713,
  journal: [
    {
      entry_type: "REVERSAL",
      debit_account: "GL-1450-FRAUD-SUSPENSE",
      credit_account: "******1233",
      amount_rm: 890,
      posted_by: "agent:resolver",
    },
  ],
  events: [
    [1, "CASE_RECEIVED", "agent:intake"],
    [2, "INTAKE_EXTRACTED", "agent:intake"],
    [3, "CLASSIFIED", "agent:classifier"],
    [4, "VERIFICATION_COMPLETED", "agent:verifier"],
    [5, "GATE_DECISION", "kernel"],
    [6, "JOURNAL_POSTED", "agent:resolver"],
    [7, "DRAFT_LINTED", "kernel"],
    [8, "MESSAGE_SENT", "agent:communicator"],
  ].map(([seq, event_type, actor]) => ({
    seq: seq as number,
    event_type: event_type as string,
    actor: actor as string,
    payload:
      event_type === "GATE_DECISION"
        ? {
            reasons: ["Verification returned PASS against the core banking record."],
            citations: ["unauthorized_transaction.resolution.require_verification = PASS"],
          }
        : {},
    prev_hash: seq === 1 ? "0".repeat(64) : `previous-${seq}`,
    hash: `8a3f${String(seq).padStart(2, "0")}${"c9e7".repeat(14)}`,
  })),
};
