export const demoScenes = [
  {
    id: "title",
    kicker: "AI AGENT TRACK / CASE STUDY 1",
    title: "CaseZero",
    caption: "Bank disputes resolved in minutes, governed end to end.",
    durationMs: 20000,
    narration: "This is CaseZero, built for the AI Agent Track and Case Study One. It is a governed dispute operating system for a five-person, non-technical bank complaints team. Axiom can prepare work in natural language, but it cannot invent authority, bypass a gate, or move money by itself.",
  },
  {
    id: "pain",
    kicker: "REAL-WORLD SCENARIO INSIGHT",
    title: "The clock starts before anyone understands the case.",
    caption: "1.8 million customers · 90 minutes per case · 11% missed deadlines",
    durationMs: 30000,
    narration: "The scenario bank serves one point eight million retail and SME customers. Today, one dispute takes about ninety minutes across email, documents, core banking, CRM and several departments. Eleven percent of regulatory deadlines are missed. Bank Negara Malaysia and FMOS timelines run from five to twenty working days. The problem is not a lack of chat. It is fragmented evidence, unclear ownership and slow controlled execution.",
  },
  {
    id: "architecture",
    kicker: "AI INNOVATION / 30 POINTS",
    title: "Six agents propose. One kernel decides.",
    caption: "Parallel specialists · typed proposals · deterministic authority gates",
    durationMs: 30000,
    narration: "CaseZero uses six specialists for intake, classification, evidence verification, resolution, customer communication and SLA supervision. They can work in parallel and return typed proposals. A deterministic kernel owns the irreversible decisions. That boundary is the central innovation: models propose, the kernel disposes. It gives the speed of agents without granting a probabilistic model financial or compliance authority.",
  },
  {
    id: "onboarding",
    kicker: "FIRST SHIFT",
    title: "The stakeholder starts with decisions, not agent internals.",
    caption: "One guided entry point · synthetic rehearsal · no bank data required",
    durationMs: 25000,
    narration: "A new stakeholder lands on a first-shift guide, not a developer console. It says what needs attention, what automation may do, and what remains under human control. The public rehearsal uses synthetic data and makes no bank-data changes. Staff can explore immediately, while real operators later join with a work-email invitation and least-privilege role.",
  },
  {
    id: "human_queue",
    kicker: "SIMPLE WORKSPACE",
    title: "Only the exceptions need a person.",
    caption: "Category · urgency · SLA · evidence · next decision",
    durationMs: 30000,
    narration: "The simple workspace is designed for the complaints officer. It collapses the pipeline into the few cases that need a person. Each card carries category, urgency, deadline, evidence state and the next decision. Intake has already parsed RFC eight-two-two email and PDF evidence, applied a pre-model injection firewall, encrypted personal data and produced a deterministic extraction record.",
  },
  {
    id: "mission_control",
    kicker: "MISSION CONTROL",
    title: "See the pressure before it becomes a breach.",
    caption: "Continuous case state · SLA forecast · agent health · measured evaluation",
    durationMs: 35000,
    narration: "Mission Control gives the stakeholder the operating picture. Cases move through a continuous state model; there is no hidden lane. The supervisor forecasts SLA pressure from deadlines and human workload. The view also exposes agent health and persisted evaluation results. Pro mode is denser for oversight, while mobile and Simple mode keep one active stage visible for day-to-day work.",
  },
  {
    id: "axiom",
    kicker: "AXIOM BY CASEZERO",
    title: "Ask. Inspect authority. Then act.",
    caption: "Axiom shows capability, role, effect and gates before execution.",
    durationMs: 35000,
    narration: "Axiom is agentic, but deliberately not magical. The operator asks to verify a case. Before anything runs, Axiom shows the named capability, whether the request changes state, the required role and every gate still in force. The server replans the command, checks the role, requires confirmation for governed changes and returns a receipt. Axiom has no direct posting capability. Money still requires PASS evidence and a signed kernel ticket.",
  },
  {
    id: "customer",
    kicker: "CUSTOMER OUTCOME",
    title: "The customer sees the outcome, not the machinery.",
    caption: "Pre-filled dispute · PASS-gated adjustment · plain language · FMOS rights",
    durationMs: 30000,
    narration: "Here a customer rejects a proactive transaction alert. CaseZero files the pre-filled dispute, verifies the transaction evidence, and posts a two-thousand-four-hundred-and-fifty-ringgit adjustment only after the PASS gate. The customer receives a calm status page and plain-language reason. The communication layer lints every draft and preserves the FMOS right to refer an eligible dissatisfied claim within six months.",
  },
  {
    id: "audit",
    kicker: "TECHNICAL EXCELLENCE",
    title: "Trust the chain, not the screen.",
    caption: "Tamper location named · chain voided · unsafe intake quarantined pre-LLM",
    durationMs: 30000,
    narration: "The Audit Explorer verifies a continuous SHA-two-fifty-six chain. This rehearsal alters sequence four. The screen does not merely show a warning; it names the broken link and marks the derived view void. Injection attempts are quarantined before a model call, so hostile instructions never enter extraction or classification. Financial postings also require a balanced double-entry journal.",
  },
  {
    id: "settings",
    kicker: "STAKEHOLDER CONTROL REGISTER",
    title: "Change the operation. Keep the controls visible.",
    caption: "Bank identity · SLA horizon · Axiom switch · automatic-resolution kill switch",
    durationMs: 30000,
    narration: "Settings belong to the stakeholder, not to a hidden environment file. An Admin can change the bank display name, complaints contact, operating timezone, default workspace and SLA warning horizon. Axiom and automatic financial resolution have separate authority switches. Every change is server-validated and hash-chained. In rehearsal, the interface issues a receipt without changing the live register.",
  },
  {
    id: "operators",
    kicker: "ACCESS + HANDOFF",
    title: "One work email creates one least-privilege operator.",
    caption: "Admin invitation · explicit role · no public self-registration",
    durationMs: 30000,
    narration: "This is how bank staff add their emails. The first Admin is provisioned during the controlled deployment handoff. That Admin opens Operators, enters a colleague's work email, selects the least-privilege role and sends the invite through Supabase authentication. There is no open public registration. The rehearsal proves the flow without sending email or creating a real account.",
  },
  {
    id: "proof",
    kicker: "RELEASE EVIDENCE",
    title: "Measured, not merely demonstrated.",
    caption: "95.90% category · 98.97% urgency · 5/5 attacks blocked · 465 backend tests",
    durationMs: 25000,
    narration: "The persisted live-model evaluation scores ninety-five point nine percent category accuracy and ninety-eight point nine-seven percent urgency accuracy across one hundred and ninety-five clean cases. All five injection attacks are blocked. Median model latency is two point six seconds, measured cost is about one-tenth of a sen per case, and the release carries four hundred and sixty-five backend tests plus eleven browser journeys.",
  },
  {
    id: "close",
    kicker: "CONTROLLED ROLLOUT",
    title: "Ready for a synthetic pilot today.",
    caption: "Core + CRM credentials · mailbox · compliance sign-off · first Admin identity",
    durationMs: 20000,
    narration: "The first controlled rollout targets unauthorised transactions and billing errors, together fifty-seven percent of scenario volume, with a stretch goal from ninety minutes to under five. CaseZero is ready for a synthetic pilot. Live rollout needs core and CRM credentials, the complaints mailbox, Compliance sign-off and the first Admin identity.",
  },
];

export const demoSceneById = Object.fromEntries(demoScenes.map((scene) => [scene.id, scene]));
